server:
  port: 9010
spring:
  application:
    name: ums

eea:
  security:
    authenticatedRequest: /user/checkAccess,/user/resources*,/user/add_user_to_resource
    roleProtectedRequest:
      DATA_CUSTODIAN: /resource/create,/resource/delete*,/user/add_contributor_to_resource